- name: Create linux user 
  user: 
    name: Morand
    state: present
    password: "{{'password' | password_hash('sha512')}}"

- name: Read CSV file
  community.general.read_csv:
    path: "roles/password_gestion/files/password_vault.csv"
  register: users
  
- name: Display CSV rows
  debug: 
    msg: "User: {{item.username}}, password: {{item.old_password}}"
  loop: "{{users.list}}"
  loop_control:
    loop_var: item
  prompt: "Choose a user"
  when: item.username == demande

- name: Generate new password
  set_fact:
    new_password: "{{lookup('password', length=14 chars=ascii_letters,digits')}}"
  when: item.username == demande
  loop: "{{users.list}}"
  loop_control:
    loop_var: item

- name: Update password on CSV file
  ansible.builtin.replace:
    path: "roles/password_gestion/files/password_vault.csv"
    regexp: "{{item.old_password}}"
    replace: "{{new_password}}"
  loop: "{{users.list}}"
  loop_control:
    loop_var: item
  when: item.username == demande

- name: Update password on remote machine
  ansible.builtin.user:
    name: "{{demande}}"
    password: "{{new_password}}"
    update_password: always
  when: new_password is defined

- name: Check is password has been updated
  ansible.builtin.shell: "echo'{{new_password}}' | sudo -S -k chpasswd"
  register: password_changed
  ignore_errors: true

- name: Display check result
  debug:
    msg: "Password has been updated: {{password_changed.changed}}"
