- name: Check Windows SNMP service is running
  win_service:
    name: SNMP
    state: started
  
- name: Add Windows host to Centreon
  centreon_host:
    url: "{{ centreon_url }}"
    username: "{{ centreon_api_user }}"
    password: "{{ centreon_api_pass }}"
    name: "{{ centreon_name }}"
    alias: "{{ centreon_alias }}"
    ipaddr: "{{ ansible_host }}"
    hosttemplates:
      - name: OS-Windows-SNMP-custom
    status: enabled
    state: present
  delegate_to: 10.0.4.2
  remote_user: root
