- name: Windows remove configuration
  win_feature:
    name: SNMP-Service
    state: absent

- name: Remove Centreon configuration
  centreon_host:
    url: "{{centreon_url}}"
    username: "{{centreon_api_user}}"
    password: "{{centreon_api_pass}}"
    name: "{{centreon_name}}"
    alias: "{{centreon_alias}}"
    ipaddr: "{{centreon_alias}}"
    state: absent
  delegate_to: 10.0.4.2
  remote_user: root
