- name: Linux SNMP Installation
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - snmp
    - snmpd
- name: starting Linux SNMP Daemon service
  service:
    name: snmpd
    state: started
    enabled: yes
