- name: Check Linux SNMP service is running
  service:
    name: snmpd
    state: started
    enabled: yes
  
- name: Add host to Centreon
  centreon_host:
    url: "{{ centreon_url }}"
    username: "{{ centreon_api_user }}"
    password: "{{ centreon_api_pass }}"
    name: "{{ centreon_name }}"
    alias: "{{ centreon_alias }}"
    ipaddr: "{{ ansible_host }}"
    hosttemplates:
      - name: OS-Linux-SNMP-custom
    status: enabled
    state: present
  delegate_to: 10.0.4.2
