- name: Check Linux SNMP service is running
  service:
    name: snmpd
    state: started
    enabled: yes

- name: Add Hostgroup for Linux
  centreon_hostgroup:
    url: "{{ centreon_url }}"
    username: "{{ centreon_api_user }}"
    password: "{{ centreon_api_pass }}"
    hg:
      - name: Linux-Server
        alias: Linux Server
  delegate_to: 10.0.4.2
  run_once: true
  
- name: Add host to Centreon
  centreon_host:
    url: "{{ centreon_url }}"
    username: "{{ centreon_api_user }}"
    password: "{{ centreon_api_pass }}"
    name: "{{ ansible_hostname }}"
    alias: "{{ ansible_fqdn }}"
    ipaddr: "{{ ansible_host }}"
    hosttemplates:
      - name: OS-Linux-SNMP-custom
    status: enabled
    state: present
  delegate_to: 10.0.4.2
