- name: "Centreon Supervision"
  hosts: 
    - Linux
    - Windows
  gather_facts: False
  remote_user: "{{'Administrateur' if inventory_hostname in groups['Windows'] else 'root'}}"
  vars_files:
    - vars/main.yml
  roles:
    - role: ansible-modules-centreon
    - role: centreon_supervise
      tags: [centreon]
