- name: "Remove Configuration"
  hosts: 
    - Linux
    - Windows
  remote_user: "{{'Administrateur' if inventory_hostname in groups['Windows'] else 'root'}}"
  gather_facts: False
  vars_files:
    - vars/main.yml
  roles:
    - role: ansible-modules-centreon
    - role: remove_configuration
      tags: [remove]
